### ISSUE TITLE
Add an automatic program stepper. this ideally will allow for adjustable stepping

### ISSUE THREAD

**Issue by CarmanK** [clbx/Cosmic#11]

**Comment by clbx** [comment]
I'm implementing this right now

**Comment by clbx** [comment]
Added a Run and Pause button, adjustable speeds might be difficult. Also is currently limited by the frame-rate of the GUI effectively limiting the processor to 60hz, will need to figure out a way to balance this.

**Comment by clbx** [comment]
little hacky, but it works good
