### ISSUE TITLE
16 Bit MOV Instructions don't write to the proper registers

### ISSUE THREAD

**Issue by clbx** [clbx/Cosmic#16]
Currently 16 bit MOV just writes to the register +1 so if 2 is given, it'll write to 2 and 3 instead of 3 and 4.

Not sure how we want to handle this or if it/ how it should be taken care of in the assembler

**Comment by clbx** [comment]
This also goes alone with #17

**Comment by CarmanK** [comment]
Should be fixed along with issue #17
