### ISSUE TITLE
Make Register Access Consistent

### ISSUE THREAD

**Issue by clbx** [clbx/Cosmic#17]
Some Instructions when given R1 take from r[0], some take from r[1]. 

Example:
MOV R0 points to [0]
JMP R0 points to [1]

A proper way should be decided and made uniform

**Comment by clbx** [comment]
The given example is wrong. The issue is actually between two MOV functions.

**Comment by clbx** [comment]
0x39 and 0x33 use registers differently

**Comment by clbx** [comment]
Should check the following 

https://github.com/clbx/Cosmic/blob/4c5f7c71501ca2fcbd31ec2f7162efb6d158f4e7/src/cosproc.cpp#L353-L362

And all similar uses

https://github.com/clbx/Cosmic/blob/4c5f7c71501ca2fcbd31ec2f7162efb6d158f4e7/src/cosproc.cpp#L728-L732

and all similar uses

**Comment by CarmanK** [comment]
Fixed
