### ISSUE TITLE
Create CLI

### ISSUE THREAD

**Issue by clbx** [clbx/Cosmic#39]
Create CLI to run over SSH on Pi

Either using curses or ImTui

**Comment by ggerganov** [comment]
If you run into any issues with the ImTui integration or if you have suggestions how to improve it - feel free to open an issue. Any feedback is appreciated!

**Comment by clbx** [comment]
Thanks @ggerganov!

**Comment by clbx** [comment]
Demoted to low priority since ImGui using OpenGL2 works great on the Pi (At least the Pi 4)
