### ISSUE TITLE
Add Keyboard Support

### ISSUE THREAD

**Issue by clbx** [clbx/Cosmic#53]
Allow keyboard input to be given through the video out window (probably should rename that too)

Keyboard functionality will use 2 bytes, one to give the character given to the keyboard allowing for 256 different characters, the other to use for status. The only current planned use of the status byte is to flag when a new character is added.

**Comment by CarmanK** [comment]
Implemented for Video Out.

Keeping this open until focus for other shortcuts is added now that its easy enough to implement using the method used for video out
