### ISSUE TITLE
MacOS BigSur: won't compile

### ISSUE THREAD

**Issue by janroesner** [clbx/Cosmic#62]
Awesome project gentlemen. Any chance you can update the source, so it compiles properly on BigSur and higher?

**Comment by clbx** [comment]
It’s been a while since I touched it, but sure.

I only have a Monterey machine now, I’ll get it to compile there and hopefully that’ll work for Big Sur

**Comment by clbx** [comment]
@janroesner I was able to get it to compile with the change I just pushed up. I think somewhere in the last two years brew changed where it puts includes.

Give that a try and let me know if you are able to build!

**Comment by janroesner** [comment]
@clbx, thanks for putting effort into this!

On my M1 the build process complains about the use of `__builtin_ia32_emms` which is not defined. But this is only due to the fact, that I tried to create a native arm64 build. As soon as I run make targeting x86_64, I get a number of warnings, but Cosmic works like a charme.

So for everyone with the same issue: `brew install sdl2 && arch -x86_64 make` does the trick.

**Comment by clbx** [comment]
Yeah it spits out a lot of warnings, but they’re not something I’m interested in fixing unless it effects functionality, in which case feel free to open an issue
